module AbstractList
  def self.sample
    self.list.sample
  end

  def self.list
    []
  end
end

module FloralPrefixList
  def self.list
    [
      'Abrams\'s',
      'Achemilla-leaved',
      'Alderney',
      'Algodones',
      'Alkali',
      'Alpine',
      'Angel',
      'Appalachian',
      'Arctic',
      'Arizona',
      'Ashy',
      'Aspen',
      'Autumn',
      'Baby',
      'Ball-head',
      'Barren',
      'Baytop\'s',
      'Bear\'s',
      'Beautiful',
      'Beegum',
      'Bigflower',
      'Black Button',
      'Black',
      'Blue Mountain',
      'Blue Wine',
      'Blue',
      'Bluff',
      'Bolander\'s',
      'Bonnet',
      'Boulder Mountain',
      'Branched',
      'Brandegee\'s',
      'Broadstemmed',
      'Brook',
      'Bulb',
      'Burlew\'s',
      'Burnt Cape',
      'Bushy',
      'Busy',
      'Butterfly Blue',
      'California',
      'Canadian',
      'Carolina',
      'Cascade',
      'Ceylon',
      'Challenger',
      'Cheerful',
      'Chinese',
      'Christmas',
      'Clary',
      'Cliff',
      'Coastal',
      'Colorado',
      'Columbian',
      'Combleaf',
      'Common',
      'Congo',
      'Cornleaf',
      'Cottam\'s',
      'Creeping',
      'Crested',
      'Crinkled',
      'Crow',
      'Cucumberleaf',
      'Cultivated',
      'Cusick\'s',
      'Cutleaf',
      'Czelghaurian',
      'Daffodil',
      'Daphne\'s',
      'Dark Red',
      'Desert',
      'Diamond',
      'Divided',
      'Diviner\'s',
      'Dotted',
      'Douglas\'s',
      'Downy',
      'Drummond\'s',
      'Dune',
      'Dusky',
      'Dwarf Mountain',
      'Dwarf',
      'Early',
      'Eastern',
      'Eggert\'s',
      'Elegant',
      'Elemendorf\'s',
      'English',
      'Erect',
      'European',
      'Everlasting',
      'Fan-foil',
      'Fanleaf',
      'Fewleaf',
      'Field',
      'Fire Sprite',
      'Florida',
      'Foxhollow',
      'Fragile',
      'Fringed',
      'Garden',
      'German',
      'Geyer\'s',
      'Giant',
      'Gland',
      'Glassy',
      'Golden',
      'Gooding\'s',
      'Grand Coulee',
      'Gray\'s',
      'Greek',
      'Grey',
      'Guatamalan',
      'Hairy',
      'Hickman\'s',
      'High Mountain',
      'Himalayan',
      'Hoary',
      'Honey Gem',
      'Hong Kong',
      'Hooker\'s',
      'Hopwood\'s',
      'Horse',
      'Howell\'s',
      'Hummingbird',
      'Hybrid',
      'Ice',
      'Indian',
      'Intermediate',
      'Italian',
      'Jakeside',
      'Jamaican',
      'Japanese',
      'Jenny',
      'Jerusalem',
      'Jungle',
      'Kashmir',
      'Keeled',
      'Kern',
      'Kilimanjaro',
      'Lady\'s',
      'Lax-flowered',
      'Lebanese',
      'Lemmon\'s',
      'Little River Canyon',
      'Little',
      'Longleaf',
      'Macedonian',
      'Macoun\'s',
      'Mallow',
      'Manyflower',
      'Marsh',
      'Matted',
      'Maximillian',
      'Meadow',
      'Mediterranean',
      'Mexicali',
      'Mexican Bush',
      'Minnow',
      'Miyama-rakkyo',
      'Mock',
      'Molly',
      'Moonlight',
      'Morefield\'s',
      'Mountain Meadow',
      'Mountain',
      'Mouse',
      'Muck',
      'Munz\'s',
      'Myretoun',
      'Narrowleaf',
      'Neglected',
      'Nevada',
      'Nevius\'s',
      'New Guinea',
      'New Mexico',
      'Newberry\'s',
      'Noble',
      'Nodding',
      'Northern',
      'Norwegian',
      'Nuttall\'s',
      'Oldfield',
      'Oneflower',
      'Oneleaf',
      'Orange Marmalade',
      'Orange',
      'Otaheite',
      'Pale',
      'Paleleaf',
      'Papery',
      'Paradox',
      'Parish\'s',
      'Parrot',
      'Parry\'s Fringed',
      'Passey\'s',
      'Peaches-and-Cream',
      'Pennsylvania',
      'Perez\'s',
      'Persian',
      'Pietvar',
      'Pilot Range',
      'Pine',
      'Pink',
      'Pitted',
      'Plains',
      'Platte River',
      'Policeman\'s',
      'Poor Man\'s',
      'Porter\'s',
      'Prarie',
      'Pretty',
      'Purple',
      'Purpledisk',
      'Rat-tail',
      'Red Root',
      'Red',
      'Reddish',
      'Rescindot',
      'Robbin\'s',
      'Robinson\'s',
      'Robyn Gordon',
      'Rock',
      'Rosalie',
      'Rosinweed',
      'Rosy',
      'Rough',
      'Rough-fruited',
      'Round-headed',
      'Royal Star',
      'Runyon\'s',
      'Russian',
      'Rydberg\'s',
      'Saltmarsh',
      'San Bernardino',
      'Sanborn\'s',
      'Sand',
      'Saw',
      'Sawtooth',
      'Scarlet',
      'Schubert\'s',
      'Schumacher',
      'Schweinitz\'s',
      'Scytheleaf',
      'Sea',
      'Serpentine',
      'Sheep',
      'Shortstyle',
      'Showy',
      'Sicilian',
      'Sierran',
      'Silky',
      'Silver',
      'Silverleaf',
      'Silvery',
      'Slender',
      'Small Woodland',
      'Smith\'s',
      'Smooth',
      'Snow',
      'Snowy',
      'Soft',
      'South Idaho',
      'Southeastern',
      'Southern',
      'Spotted',
      'Spreading',
      'Spring',
      'Springwood',
      'Spurless',
      'Square-stem',
      'Stag\'s',
      'Sticky',
      'Stiff',
      'Strawberryleaf',
      'Striped',
      'Sulphur',
      'Sunshine',
      'Superb',
      'Swamp',
      'Tanners Canyon',
      'Tansy',
      'Tapertip',
      'Texas',
      'Textile',
      'Three-cornered',
      'Threebact',
      'Tongue',
      'Trailing',
      'Transpecos',
      'Tree',
      'Triquetous',
      'Twincrest',
      'Twinleaf',
      'Twoflower',
      'Téte-á-Téte',
      'Umbrella',
      'Vahl\'s',
      'Variable',
      'Variableleaf',
      'Varileaf',
      'Victory',
      'Villious',
      'Wavyleaf',
      'Welsh',
      'Western',
      'Westwood',
      'White',
      'Whiteleaf',
      'Whorled',
      'Wild',
      'Willowleaf',
      'Woodland',
      'Woolly',
      'Yellow',
      'Yosemite',
    ]
  end
end

module FlowerNameList
  def self.list
    [
      'Abbotswood',
      'Acacia',
      'Allspice',
      'Apple',
      'Azalea',
      'Balsam',
      'Barberry',
      'Basketflower',
      'Bean',
      'Bedstraw',
      'Begonia',
      'Bluet',
      'Brush Cherry',
      'Burdock',
      'Buttercup',
      'Cactus',
      'Campion',
      'Cassia',
      'Catchfly',
      'Centaury',
      'Centory',
      'Cherry',
      'Chives',
      'Cinquefoil',
      'Clove',
      'Coffee',
      'Coralberry',
      'Cornflower',
      'Croton',
      'Crowfoot',
      'Cyrtandra',
      'Eggplant',
      'Eucalyptus',
      'Everlasting',
      'Feijoa',
      'Fig',
      'Galingale',
      'Garlic',
      'Geranium',
      'Glory Bush',
      'Gloxinia',
      'Goat\'s-thorn',
      'Groundsel',
      'Guava',
      'Gum Tree',
      'Heath',
      'Heather',
      'Helichrysum',
      'Hop',
      'Horsenettle',
      'Imaptiens',
      'Ironweed',
      'Jewelweed',
      'Kava',
      'Knapweed',
      'Lavender',
      'Leafflower',
      'Leek',
      'Lilly Pilly',
      'Lily',
      'Locoweed',
      'Loggerhead',
      'Madder',
      'Marlberry',
      'Milkvetch',
      'Milkwort',
      'Millet',
      'Morning Glory',
      'Myrtle',
      'Nettle',
      'Nightshade',
      'Oak',
      'Onion',
      'Orchid',
      'Pea',
      'Pepper',
      'Pepperleaf',
      'Persimmon',
      'Pincushion',
      'Pohutukawa',
      'Potato',
      'Ragwort',
      'Rangan',
      'Rattlebox',
      'Rattlepod',
      'Rhododendron',
      'Rose',
      'Rosemary',
      'Rushfoil',
      'Sage',
      'Satinash',
      'Screwpine',
      'Sedge',
      'Shapweed',
      'Shrimp Plant',
      'Snakeroot',
      'Snapdragon',
      'Sorrel',
      'Spath',
      'Spearwort',
      'Spider Flower',
      'Spurge',
      'Starry-eyes',
      'Stopper',
      'Strawberry',
      'Sunflower',
      'Switchgrass',
      'Thistle',
      'Thorntree',
      'Tomato',
      'Tormentil',
      'Touch-me-not',
      'Water-willow',
      'Waterberry',
      'Wattle',
      'Whistling Thorn',
      'Yam',
      'Chia'
    ]
  end
end

module LifeCycleTypeList
  def self.list
    [
      'Annual',
      'Biennual',
      'Perrenial'
    ]
  end
end

module FruitTypeList
  def self.list
    [
      'VW bus',
      'character from a Willa Cather novel',
      'achene',
      'backhoe',
      'baseball',
      'berry',
      'brand of crab juice',
      'capsule',
      'caryopsis',
      'cigar',
      'cotton gin',
      'crystal',
      'dance style',
      'diamond',
      'drupe',
      'eclair',
      'grain silo',
      'gruyere',
      'hospital',
      'jade ring',
      'lean-to',
      'legume',
      'macaroon',
      'marble',
      'mustache',
      'news anchor',
      'nut',
      'pebble',
      'pillbox',
      'placenta',
      'pulley',
      'neutron star',
      'samara',
      'sausage',
      'saxophone',
      'schizocarp',
      'secret society',
      'sense of dread',
      'set of platform heels',
      'silicle',
      'silique',
      'spinal column',
      'mountain spring',
      'swan\'s egg',
      'ulnar nerve',
      'utricle',
      'vermouth salesman',
      'wild stallion',
    ]
  end
end

module FlavorList
  def self.sample
    self.list.sample
  end

  def self.list
    [
      "A-1 sauce",
      "Bearnaise sauce",
      "Hollandaise sauce",
      "Sour Patch Kids",
      "absinthe",
      "acorns",
      "ants",
      "bacon",
      "barbed wire",
      "beeswax",
      "birthday cake",
      "bitters",
      "blood",
      "brass",
      "bread",
      "brown sugar",
      "burning",
      "butter",
      "butterscotch",
      "car exhaust",
      "cardboard",
      "chalk",
      "charcoal",
      "cheese rind",
      "chili oil",
      "circuitry",
      "clover",
      "crickets",
      "darkness",
      "death",
      "desire",
      "deviled eggs",
      "earth",
      "eggs",
      "electricity",
      "ennui",
      "espresso",
      "exhaust",
      "feathers",
      "fish",
      "french fries",
      "fried chicken",
      "fruit roll-ups",
      "hair",
      "horse sweat",
      "human skin",
      "ice",
      "industrial chemicals",
      "ink",
      "latkes",
      "leek-and-potato soup",
      "logic",
      "marshmallows",
      "mold",
      "mothballs",
      "newspaper",
      "nickels",
      "peach candy",
      "pencil shavings",
      "pennies",
      "pickled apricots",
      "pork cheeks",
      "red meat",
      "rocks",
      "salmon roe",
      "salt",
      "shoes",
      "shrimp",
      "snowflakes",
      "sriracha",
      "sturgeon roe",
      "sunlight",
      "symbolic logic",
      "taffy",
      "tequila",
      "treasure",
      "truffles",
      "vinegar",
      "communion wafer",
      "wants",
      "watermelon soda",
      "wind",
      "wine",
      "wood",
      "wool",
      "yak fur",
      "yak must",
    ]
  end
end

module ColorList
  def color_list
    [
      'Blue',
      'Brown',
      'Green',
      'Grey',
      'Orange',
      'Pink',
      'Red',
      'Violet',
      'Yellow',
    ]
  end
end

module ScentList
  def self.list
    [
      "acai berry",
      "acetone",
      "aloe vera",
      "aloe",
      "amber",
      "ambrosia",
      "baby lotion",
      "baby powder",
      "bacon",
      "baked bread",
      "baked pie crust",
      "beer",
      "bleach",
      "bourbon",
      "brown sugar",
      "brownie",
      "bubblegum",
      "burnt rubber",
      "butter creme",
      "buttered popcorn",
      "butterscotch",
      "cabernet",
      "camphor",
      "candy corn",
      "caramel apple",
      "carrion",
      "celery",
      "champagne",
      "chlorine",
      "chocolate",
      "cinnamon",
      "citron",
      "citronella",
      "coca cola",
      "coconut",
      "cool water",
      "creamsicle",
      "creme brulee",
      "creme de cocoa",
      "creme de menthe",
      "cucumber",
      "cupcakes",
      "dark chocolate",
      "dirt",
      "dragon's blood",
      "dreamsicle",
      "earth",
      "eggnog",
      "english toffee",
      "eucalyptus",
      "fern",
      "frankincense",
      "fresh bread",
      "fresh cut grass",
      "fresh laundry",
      "fresh linen",
      "fresh rain",
      "fruit slices",
      "ginger",
      "gingerbread",
      "glue",
      "grass",
      "green tea",
      "guava",
      "hemp",
      "honey",
      "honeydew melon",
      "honeydew",
      "horse",
      "huckleberry",
      "icy mint",
      "ivy",
      "key lime pie",
      "kiwi melon",
      "kiwi",
      "lavender",
      "leather",
      "lemongrass",
      "licorice",
      "lime leaf",
      "lime",
      "maple syrup",
      "margarita",
      "marijuana",
      "marshmallow",
      "menthol",
      "milk & honey",
      "mint",
      "mistletoe",
      "motor oil",
      "mountain air",
      "mulberry",
      "musk",
      "myrrh",
      "nag champa",
      "new car",
      "new mown hay",
      "oatmeal",
      "ocean water",
      "oriental musk",
      "patchouli",
      "peanut butter cups",
      "peanut butter",
      "pecan",
      "pikaki",
      "pine needles",
      "pine",
      "pineapple",
      "pizza",
      "play doh",
      "popcorn",
      "praline",
      "rain forest",
      "rain",
      "roasted pine cone",
      "root beer",
      "rosemary",
      "rosewood",
      "rum",
      "sandalwood",
      "sassafras",
      "sea breeze",
      "sea mist",
      "seashore",
      "sewage",
      "sheer musk",
      "snowflake",
      "sugar cane",
      "sulphur",
      "snow cone",
      "tea tree",
      "teaberry",
      "the sea",
      "kopan masala",
      "tobacco",
      "vetiver",
      "Vicks VapoRub",
      "watermelon",
      "waves",
      "white ginger",
      "white tea",
      "wood smoke",
      "woodburning fireplace",
      "Woodstock",
      "zucchini bread",
    ]
  end
end

module FlowerShapeList
  def self.list
    [
      "bell",
      "bow",
      "butterfly",
      "cross",
      "pea",
      "saucer",
      "star",
      "trumpet",
      "tube",
      "urn"
    ]
  end
end

module FlowerGroupList
  def self.list
    [
      'bands',
      'braids',
      'bunches',
      'clusters',
      'helices',
      'infloresences',
      'knots',
      'spirals',
      'sprays'
    ]
  end
end

module FlowerTextureList
  def self.list
    [
      "bristly",
      "bumpy",
      "delicate",
      "dimpled",
      "feathery",
      "fuzzy",
      "greasy",
      "hairy",
      "tough",
      "leathery",
      "oily",
      "powdery",
      "prickly",
      "rubbery",
      "silky",
      "soft",
      "spongy",
      "spurred",
      "velvety"
    ]
  end
end

class FlowerColorList
  include ColorList
  def initialize
    @colors = self.color_list.shuffle
    @colors = @colors.map {|color| color.downcase}
  end

  def list
    [
      "#{@colors.pop}",
      "bicolor #{@colors.pop}-#{@colors.pop}",
      "white",
      "white-to-#{@colors.pop}"
    ]
  end
end

module FlowerSizeList
  def self.list
    [
      "#{rand(1..4)} cm in diameter",
      "big",
      "diminutive",
      "enormous",
      "giant",
      "gigantic",
      "huge",
      "humongous",
      "immense",
      "large",
      "massive",
      "microscopic",
      "petite",
      "plentiful",
      "scrawny",
      "small",
    ]
  end
end

module AnimalList
  def self.list
    [
      "Californians",
      "Chansey",
      "Cubone",
      "Fennekin",
      "Londoners",
      "New Yorkers",
      "Rapidash",
      "Sylveon",
      "Texans",
      "Tokyoites",
      "alligators",
      "alpaca",
      "antelope",
      "ants",
      "apes",
      "armadillos",
      "bats",
      "beavers",
      "bees",
      "bison",
      "butterflies",
      "capybaras",
      "caribou",
      "cats",
      "cattle",
      "chickens",
      "chimps",
      "cockroaches",
      "cod",
      "crabs",
      "deer",
      "dogs",
      "dolphins",
      "ducks",
      "eagles",
      "eels",
      "fat ponies",
      "foxes",
      "geese",
      "gerbils",
      "hamsters",
      "heads of state",
      "hedgehogs",
      "herons",
      "horses",
      "hummingbirds",
      "jellyfish",
      "kangaroos",
      "lemurs",
      "locusts",
      "manatees",
      "mice",
      "moose",
      "narwhals",
      "owls",
      "pandas",
      "panthers",
      "parrots",
      "penguins",
      "pigs",
      "rabbits",
      "raccoon dogs",
      "raccoons",
      "red pandas",
      "salmon",
      "sheep",
      "skunks",
      "starfish",
      "starlings",
      "swans",
      "tapirs",
      "termites",
      "tigers",
      "wasps",
      "weasels",
      "wolves",
      "wombats",
      "yaks",
      "zebras"
    ]
  end
end

module FlowerAdjectivesWithoutAreList
  def self.list
    [
      "smell of #{ScentList.list.sample}",
      "grow in #{FlowerGroupList.list.sample} of #{rand(1..3)}-#{rand(4..9)}",
      "have #{rand(4..12)} petals",
      "attract #{AnimalList.list.sample}"
    ]
  end
end

module EdibilityList
  def self.list
    [
      "Edible.",
      "Mildly toxic.",
      "Toxic.",
      "Poisonous.",
      "Deadly poisonous.",
      "Has #{DrugList.list.sample}-like effects if #{ConsumptionMethodList.list.sample}."
    ]
  end
end

module DrugList
  def self.list
    [
      "DMT",
      "LSD",
      "alcohol",
      "amphetamine",
      "marijuana",
      "opium",
      "psylocibin",
      "salvia"
    ]
  end
end

module ConsumptionMethodList
  def self.list
    [
      "smoked",
      "eaten",
      "crushed and snorted"
    ]
  end
end
