module AbstractList
  def self.sample
    self.list.sample
  end

  def self.list
    []
  end
end

module FloralPrefixList
  def self.list
    [
      'Abrams\'s',
      'Achemilla-leaved',
      'Alderney',
      'Algodones',
      'Alkali',
      'Alpine',
      'Angel',
      'Appalachian',
      'Arctic',
      'Arizona',
      'Ashy',
      'Aspen',
      'Autumn',
      'Baby',
      'Ball-head',
      'Barren',
      'Baytop\'s',
      'Bear\'s',
      'Beautiful',
      'Beegum',
      'Bigflower',
      'Black Button',
      'Black',
      'Blue Mountain',
      'Blue Wine',
      'Blue',
      'Bluff',
      'Bolander\'s',
      'Bonnet',
      'Boulder Mountain',
      'Branched',
      'Brandegee\'s',
      'Broadstemmed',
      'Brook',
      'Bulb',
      'Burlew\'s',
      'Burnt Cape',
      'Bushy',
      'Busy',
      'Butterfly Blue',
      'California',
      'Canadian',
      'Carolina',
      'Cascade',
      'Ceylon',
      'Challenger',
      'Cheerful',
      'Chinese',
      'Christmas',
      'Clary',
      'Cliff',
      'Coastal',
      'Colorado',
      'Columbian',
      'Combleaf',
      'Common',
      'Congo',
      'Cornleaf',
      'Cottam\'s',
      'Creeping',
      'Crested',
      'Crinkled',
      'Crow',
      'Cucumberleaf',
      'Cultivated',
      'Cusick\'s',
      'Cutleaf',
      'Czelghaurian',
      'Daffodil',
      'Daphne\'s',
      'Dark Red',
      'Desert',
      'Diamond',
      'Divided',
      'Diviner\'s',
      'Dotted',
      'Douglas\'s',
      'Downy',
      'Drummond\'s',
      'Dune',
      'Dusky',
      'Dwarf Mountain',
      'Dwarf',
      'Early',
      'Eastern',
      'Eggert\'s',
      'Elegant',
      'Elemendorf\'s',
      'English',
      'Erect',
      'European',
      'Everlasting',
      'Fan-foil',
      'Fanleaf',
      'Fewleaf',
      'Field',
      'Fire Sprite',
      'Florida',
      'Foxhollow',
      'Fragile',
      'Fringed',
      'Garden',
      'German',
      'Geyer\'s',
      'Giant',
      'Gland',
      'Glassy',
      'Golden',
      'Gooding\'s',
      'Grand Coulee',
      'Gray\'s',
      'Greek',
      'Grey',
      'Guatamalan',
      'Hairy',
      'Hickman\'s',
      'High Mountain',
      'Himalayan',
      'Hoary',
      'Honey Gem',
      'Hong Kong',
      'Hooker\'s',
      'Hopwood\'s',
      'Horse',
      'Howell\'s',
      'Hummingbird',
      'Hybrid',
      'Ice',
      'Indian',
      'Intermediate',
      'Italian',
      'Jakeside',
      'Jamaican',
      'Japanese',
      'Jenny',
      'Jerusalem',
      'Jungle',
      'Kashmir',
      'Keeled',
      'Kern',
      'Kilimanjaro',
      'Lady\'s',
      'Lax-flowered',
      'Lebanese',
      'Lemmon\'s',
      'Little River Canyon',
      'Little',
      'Longleaf',
      'Macedonian',
      'Macoun\'s',
      'Mallow',
      'Manyflower',
      'Marsh',
      'Matted',
      'Maximillian',
      'Meadow',
      'Mediterranean',
      'Mexicali',
      'Mexican Bush',
      'Minnow',
      'Miyama-rakkyo',
      'Mock',
      'Molly',
      'Moonlight',
      'Morefield\'s',
      'Mountain Meadow',
      'Mountain',
      'Mouse',
      'Muck',
      'Munz\'s',
      'Myretoun',
      'Narrowleaf',
      'Neglected',
      'Nevada',
      'Nevius\'s',
      'New Guinea',
      'New Mexico',
      'Newberry\'s',
      'Noble',
      'Nodding',
      'Northern',
      'Norwegian',
      'Nuttall\'s',
      'Oldfield',
      'Oneflower',
      'Oneleaf',
      'Orange Marmalade',
      'Orange',
      'Otaheite',
      'Pale',
      'Paleleaf',
      'Papery',
      'Paradox',
      'Parish\'s',
      'Parrot',
      'Parry\'s Fringed',
      'Passey\'s',
      'Peaches-and-Cream',
      'Pennsylvania',
      'Perez\'s',
      'Persian',
      'Pietvar',
      'Pilot Range',
      'Pine',
      'Pink',
      'Pitted',
      'Plains',
      'Platte River',
      'Policeman\'s',
      'Poor Man\'s',
      'Porter\'s',
      'Prarie',
      'Pretty',
      'Purple',
      'Purpledisk',
      'Rat-tail',
      'Red Root',
      'Red',
      'Reddish',
      'Rescindot',
      'Robbin\'s',
      'Robinson\'s',
      'Robyn Gordon',
      'Rock',
      'Rosalie',
      'Rosinweed',
      'Rosy',
      'Rough',
      'Rough-fruited',
      'Round-headed',
      'Royal Star',
      'Runyon\'s',
      'Russian',
      'Rydberg\'s',
      'Saltmarsh',
      'San Bernardino',
      'Sanborn\'s',
      'Sand',
      'Saw',
      'Sawtooth',
      'Scarlet',
      'Schubert\'s',
      'Schumacher',
      'Schweinitz\'s',
      'Scytheleaf',
      'Sea',
      'Serpentine',
      'Sheep',
      'Shortstyle',
      'Showy',
      'Sicilian',
      'Sierran',
      'Silky',
      'Silver',
      'Silverleaf',
      'Silvery',
      'Slender',
      'Small Woodland',
      'Smith\'s',
      'Smooth',
      'Snow',
      'Snowy',
      'Soft',
      'South Idaho',
      'Southeastern',
      'Southern',
      'Spotted',
      'Spreading',
      'Spring',
      'Springwood',
      'Spurless',
      'Square-stem',
      'Stag\'s',
      'Sticky',
      'Stiff',
      'Strawberryleaf',
      'Striped',
      'Sulphur',
      'Sunshine',
      'Superb',
      'Swamp',
      'Tanners Canyon',
      'Tansy',
      'Tapertip',
      'Texas',
      'Textile',
      'Three-cornered',
      'Threebact',
      'Tongue',
      'Trailing',
      'Transpecos',
      'Tree',
      'Triquetous',
      'Twincrest',
      'Twinleaf',
      'Twoflower',
      'Téte-á-Téte',
      'Umbrella',
      'Vahl\'s',
      'Variable',
      'Variableleaf',
      'Varileaf',
      'Victory',
      'Villious',
      'Wavyleaf',
      'Welsh',
      'Western',
      'Westwood',
      'White',
      'Whiteleaf',
      'Whorled',
      'Wild',
      'Willowleaf',
      'Woodland',
      'Woolly',
      'Yellow',
      'Yosemite',
    ]
  end
end

module FlowerNameList
  def self.list
    [
      'Abbotswood',
      'Acacia',
      'Allspice',
      'Apple',
      'Azalea',
      'Balsam',
      'Barberry',
      'Basketflower',
      'Bean',
      'Bedstraw',
      'Begonia',
      'Bluet',
      'Brush Cherry',
      'Burdock',
      'Buttercup',
      'Cactus',
      'Campion',
      'Cassia',
      'Catchfly',
      'Centaury',
      'Centory',
      'Cherry',
      'Chives',
      'Cinquefoil',
      'Clove',
      'Coffee',
      'Coralberry',
      'Cornflower',
      'Croton',
      'Crowfoot',
      'Cyrtandra',
      'Eggplant',
      'Eucalyptus',
      'Everlasting',
      'Feijoa',
      'Fig',
      'Galingale',
      'Garlic',
      'Geranium',
      'Glory Bush',
      'Gloxinia',
      'Goat\'s-thorn',
      'Groundsel',
      'Guava',
      'Gum Tree',
      'Heath',
      'Heather',
      'Helichrysum',
      'Hop',
      'Horsenettle',
      'Impatiens',
      'Ironweed',
      'Jewelweed',
      'Kava',
      'Knapweed',
      'Lavender',
      'Leafflower',
      'Leek',
      'Lilly Pilly',
      'Lily',
      'Locoweed',
      'Loggerhead',
      'Madder',
      'Marlberry',
      'Milkvetch',
      'Milkwort',
      'Millet',
      'Morning Glory',
      'Myrtle',
      'Nettle',
      'Nightshade',
      'Oak',
      'Onion',
      'Orchid',
      'Pea',
      'Pepper',
      'Pepperleaf',
      'Persimmon',
      'Pincushion',
      'Pohutukawa',
      'Potato',
      'Ragwort',
      'Rangan',
      'Rattlebox',
      'Rattlepod',
      'Rhododendron',
      'Rose',
      'Rosemary',
      'Rushfoil',
      'Sage',
      'Satinash',
      'Screwpine',
      'Sedge',
      'Shapweed',
      'Shrimp Plant',
      'Snakeroot',
      'Snapdragon',
      'Sorrel',
      'Spath',
      'Spearwort',
      'Spider Flower',
      'Spurge',
      'Starry-eyes',
      'Stopper',
      'Strawberry',
      'Sunflower',
      'Switchgrass',
      'Thistle',
      'Thorntree',
      'Tomato',
      'Tormentil',
      'Touch-me-not',
      'Water-willow',
      'Waterberry',
      'Wattle',
      'Whistling Thorn',
      'Yam',
      'Chia'
    ]
  end
end

module LifeCycleTypeList
  def self.list
    [
      'Annual',
      'Biennual',
      'Perrenial'
    ]
  end
end

module FruitTypeList
  def self.list
    [
      "40 year coal fire",
      "Amelia Earhart",
      "Archduke",
      "Nintendo 64 game",
      "Umwelt",
      "World Meteorological Organization",
      "blood-mare",
      "book-trade",
      "borderland",
      "butterball",
      "chin-up",
      "chowder-head",
      "chupacabra",
      "clifftop",
      "day-star",
      "demon",
      "doghouse",
      "drill bit",
      "endocrinologist",
      "eye-catcher",
      "farmyard",
      "fish slice",
      "flirtation",
      "fox-bat",
      "goblin",
      "gorehound",
      "greenhouse",
      "half-thought",
      "heart-sickness",
      "hippogryph",
      "labcoat",
      "lakebed",
      "lamb-chop",
      "man-child",
      "megamall",
      "merperson",
      "microstructure",
      "millpond",
      "mini-DV tape",
      "molar",
      "mothball",
      "mythomaniac",
      "nailgun",
      "needle-point",
      "night-cloud",
      "non-rhyming poem",
      "omelet",
      "pink hair clip",
      "plantlet",
      "playscape",
      "pleasant sensation",
      "polygraph",
      "rhubarb",
      "ritual",
      "rough barnfloor",
      "salmon fishery",
      "saltcellar",
      "sea-goddess",
      "sidequest",
      "smoke-signal",
      "soup",
      "still-life",
      "sweatdrop",
      "swordsmith",
      "taqueria",
      "tea-service",
      "telescope",
      "textbox",
      "thunderbolt",
      "tired coastguard",
      "tofu-burger",
      "tragedy",
      "trompe-l'oeil",
      "videoclip",
      "vinaigrette",
      "warp-beam",
      "weathervane",
      "webinar",
      "wee truckle-bed",
      "wingsuit",
      "wonderment",
      "woodlark",
      "work-shirt",
      "zephyr",
      "zoo",
      'K-theory',
      'Maya god',
      'VW bus',
      'academy',
      'achene',
      'airport',
      'amino acid',
      'apertif',
      'asteroid',
      'backhoe',
      'baseball',
      'berry',
      'bicycle',
      'billabong',
      'brand of crab juice',
      'button',
      'capsule',
      'caryopsis',
      'castle',
      'cat torso',
      'character from a Willa Cather novel',
      'cheekbone',
      'chrysalis',
      'cigar',
      'cornucopia',
      'cotton gin',
      'cravat',
      'crystal',
      'cummerbund',
      'dance style',
      'diamond',
      'drupe',
      'eclair',
      'eggshell',
      'egret\'s heart',
      'eyeshadow',
      'feather',
      'fictional company',
      'genetic disorder',
      'glycoprotein',
      'gotterdammerung',
      'grain silo',
      'gruyere',
      'guqin',
      'hair dye',
      'headdress',
      'hospital',
      'icy-blue lipstick',
      'jade ring',
      'knife',
      'lake',
      'lambic',
      'lean-to',
      'legume',
      'lute',
      'macaroon',
      'marble',
      'mask',
      'mead',
      'metaphysics',
      'mountain spring',
      'mountain',
      'mustache',
      'neck',
      'neutron star',
      'news anchor',
      'nomadic community',
      'nonlinear partial differential equation',
      'nut',
      'oil painting',
      'pearl',
      'pebble',
      'physical system',
      'pillbox',
      'placenta',
      'plot device',
      'pond',
      'porridge',
      'pulley',
      'purple boot',
      'religion',
      'river',
      'rouge',
      'ruby',
      'samara',
      'sapphire',
      'sausage',
      'saxophone',
      'schizocarp',
      'scholar',
      'seashell',
      'secret society',
      'sense of dread',
      'sequoia grove',
      'set of platform heels',
      'shakuhachi',
      'sheng',
      'silicle',
      'silique',
      'silver necklace',
      'small moon',
      'spinal column',
      'star',
      'swan\'s egg',
      'sweepstakes',
      'telescope',
      'text editor',
      'tiny island',
      'tongue',
      'trade union',
      'ulnar nerve',
      'utricle',
      'valkyrie',
      'valley',
      'vector space',
      'velvet cape',
      'vermouth salesman',
      'volcano',
      'whisker',
      'wig',
      'wild stallion',
      'world tree',
      'yurt',
      'zither',
    ]
  end
end

module FlavorList
  def self.sample
    self.list.sample
  end

  def self.list
    [
      "A-1 sauce",
      "Bearnaise sauce",
      "Hollandaise sauce",
      "LiveJournal",
      "Lombardy",
      "Madagascar",
      "McMurdo Station",
      "Mogadishu",
      "Neumayer-Station III",
      "Siberia",
      "Sour Patch Kids",
      "absinthe",
      "acorns",
      "ants",
      "archaeology",
      "arginine",
      "bacon",
      "baklava",
      "barbed wire",
      "beeswax",
      "birthday cake",
      "bitters",
      "blood",
      "brass",
      "bread",
      "bricks",
      "brown sugar",
      "burning",
      "butter",
      "butterscotch",
      "car exhaust",
      "cardboard",
      "chalk",
      "charcoal",
      "cheese rind",
      "childhood",
      "chili oil",
      "choral music",
      "circuitry",
      "clay",
      "clover",
      "cobwebs",
      "communion wafer",
      "crickets",
      "darkness",
      "death",
      "desire",
      "determination",
      "deviled eggs",
      "dirt",
      "early memories",
      "earth",
      "eggs",
      "electricity",
      "ennui",
      "espresso",
      "exhaust",
      "feathers",
      "fish",
      "french fries",
      "fried chicken",
      "friendship",
      "fruit roll-ups",
      "glutamate",
      "gravel",
      "hair",
      "honeysuckle",
      "horse blankets",
      "horse hooves",
      "horse sweat",
      "human skin",
      "ice",
      "industrial chemicals",
      "ink",
      "latkes",
      "lead",
      "leek-and-potato soup",
      "lemon curd",
      "lime salt",
      "logic",
      "marshmallows",
      "mold",
      "mothballs",
      "murder",
      "newspaper",
      "nickels",
      "nuclear power",
      "obsidian",
      "pastry cream",
      "peach candy",
      "pencil shavings",
      "pennies",
      "pickled apricots",
      "poetry",
      "pork cheeks",
      "psychosis",
      "radium",
      "red meat",
      "rocks",
      "saliva",
      "salmon roe",
      "salt",
      "scientific progress",
      "shoes",
      "shrimp",
      "snowflakes",
      "soil",
      "sriracha",
      "steak tartare",
      "sturgeon roe",
      "sunlight",
      "symbolic logic",
      "taffy",
      "tequila",
      "the future",
      "the ice caps",
      "tires",
      "treasure",
      "truffles",
      "truth",
      "verve",
      "vinegar",
      "wants",
      "watermelon soda",
      "wind",
      "wine",
      "wood",
      "wool",
      "yak fur",
      "yak must",
    ]
  end
end

module ColorList
  def color_list
    [
      'Blue',
      'Brown',
      'Green',
      'Grey',
      'Orange',
      'Pink',
      'Red',
      'Violet',
      'Yellow',
    ]
  end
end

module ScentList
  def self.list
    [
      "acai berry",
      "acetone",
      "aloe vera",
      "aloe",
      "amber",
      "ambrosia",
      "baby lotion",
      "baby powder",
      "bacon",
      "baked bread",
      "baked pie crust",
      "beer",
      "bleach",
      "bourbon",
      "brown sugar",
      "brownie",
      "bubblegum",
      "burnt rubber",
      "butter creme",
      "buttered popcorn",
      "butterscotch",
      "cabernet",
      "camphor",
      "candy corn",
      "caramel apple",
      "carrion",
      "celery",
      "champagne",
      "chlorine",
      "chocolate",
      "cinnamon",
      "citron",
      "citronella",
      "coca cola",
      "coconut",
      "cool water",
      "creamsicle",
      "creme brulee",
      "creme de cocoa",
      "creme de menthe",
      "cucumber",
      "cupcakes",
      "dark chocolate",
      "dirt",
      "dragon's blood",
      "dreamsicle",
      "earth",
      "eggnog",
      "english toffee",
      "eucalyptus",
      "fern",
      "frankincense",
      "fresh bread",
      "fresh cut grass",
      "fresh laundry",
      "fresh linen",
      "fresh rain",
      "fruit slices",
      "ginger",
      "gingerbread",
      "glue",
      "grass",
      "green tea",
      "guava",
      "hemp",
      "honey",
      "honeydew melon",
      "honeydew",
      "horse",
      "huckleberry",
      "icy mint",
      "ivy",
      "key lime pie",
      "kiwi melon",
      "kiwi",
      "lavender",
      "leather",
      "lemongrass",
      "licorice",
      "lime leaf",
      "lime",
      "maple syrup",
      "margarita",
      "marijuana",
      "marshmallow",
      "menthol",
      "milk & honey",
      "mint",
      "mistletoe",
      "motor oil",
      "mountain air",
      "mulberry",
      "musk",
      "myrrh",
      "nag champa",
      "new car",
      "new mown hay",
      "oatmeal",
      "ocean water",
      "oriental musk",
      "patchouli",
      "peanut butter cups",
      "peanut butter",
      "pecan",
      "pikaki",
      "pine needles",
      "pine",
      "pineapple",
      "pizza",
      "play doh",
      "popcorn",
      "praline",
      "rain forest",
      "rain",
      "roasted pine cone",
      "root beer",
      "rosemary",
      "rosewood",
      "rum",
      "sandalwood",
      "sassafras",
      "sea breeze",
      "sea mist",
      "seashore",
      "sewage",
      "sheer musk",
      "snowflake",
      "sugar cane",
      "sulphur",
      "snow cone",
      "tea tree",
      "teaberry",
      "the sea",
      "kopan masala",
      "tobacco",
      "vetiver",
      "Vicks VapoRub",
      "watermelon",
      "waves",
      "white ginger",
      "white tea",
      "wood smoke",
      "woodburning fireplace",
      "Woodstock",
      "zucchini bread",
    ]
  end
end

module FlowerShapeList
  def self.list
    [
      "bell",
      "bow",
      "butterfly",
      "cross",
      "pea",
      "saucer",
      "star",
      "trumpet",
      "tube",
      "urn"
    ]
  end
end

module FlowerGroupList
  def self.list
    [
      'bands',
      'braids',
      'bunches',
      'clusters',
      'helices',
      'infloresences',
      'knots',
      'spirals',
      'sprays'
    ]
  end
end

module FlowerTextureList
  def self.list
    [
      "bristly",
      "bumpy",
      "delicate",
      "dimpled",
      "feathery",
      "fuzzy",
      "greasy",
      "hairy",
      "tough",
      "leathery",
      "oily",
      "powdery",
      "prickly",
      "rubbery",
      "silky",
      "soft",
      "spongy",
      "spurred",
      "velvety"
    ]
  end
end

class FlowerColorList
  include ColorList
  def initialize
    @colors = self.color_list.shuffle
    @colors = @colors.map {|color| color.downcase}
  end

  def list
    [
      "#{@colors.pop}",
      "bicolor #{@colors.pop}-#{@colors.pop}",
      "white",
      "white-to-#{@colors.pop}"
    ]
  end
end

module FlowerSizeList
  def self.list
    [
      "#{rand(1..4)} cm in diameter",
      "big",
      "diminutive",
      "enormous",
      "giant",
      "gigantic",
      "huge",
      "humongous",
      "immense",
      "large",
      "massive",
      "microscopic",
      "petite",
      "plentiful",
      "scrawny",
      "small",
    ]
  end
end

module AnimalList
  def self.list
    [
      "Californians",
      "Chansey",
      "Cubone",
      "Fennekin",
      "Londoners",
      "New Yorkers",
      "Rapidash",
      "Sylveon",
      "Texans",
      "Tokyoites",
      "alligators",
      "alpaca",
      "antelope",
      "ants",
      "apes",
      "armadillos",
      "bats",
      "beavers",
      "bees",
      "bison",
      "butterflies",
      "capybaras",
      "caribou",
      "cats",
      "cattle",
      "chickens",
      "chimps",
      "cockroaches",
      "cod",
      "crabs",
      "deer",
      "dogs",
      "dolphins",
      "ducks",
      "eagles",
      "eels",
      "fat ponies",
      "foxes",
      "geese",
      "gerbils",
      "hamsters",
      "heads of state",
      "hedgehogs",
      "herons",
      "horses",
      "hummingbirds",
      "jellyfish",
      "kangaroos",
      "lemurs",
      "locusts",
      "manatees",
      "mice",
      "moose",
      "narwhals",
      "owls",
      "pandas",
      "panthers",
      "parrots",
      "penguins",
      "pigs",
      "rabbits",
      "raccoon dogs",
      "raccoons",
      "red pandas",
      "salmon",
      "sheep",
      "skunks",
      "starfish",
      "starlings",
      "swans",
      "tapirs",
      "termites",
      "tigers",
      "wasps",
      "weasels",
      "wolves",
      "wombats",
      "yaks",
      "zebras"
    ]
  end
end

module FlowerAdjectivesWithoutAreList
  def self.list
    [
      "smell of #{ScentList.list.sample}",
      "grow in #{FlowerGroupList.list.sample} of #{rand(1..3)}-#{rand(4..9)}",
      "have #{rand(4..12)} petals",
      "attract #{AnimalList.list.sample}"
    ]
  end
end

module EdibilityList
  def self.list
    [
      "Edible.",
      "Mildly toxic.",
      "Toxic.",
      "Poisonous.",
      "Deadly poisonous.",
      "Has #{DrugList.list.sample}-like effects if #{ConsumptionMethodList.list.sample}."
    ]
  end
end

module DrugList
  def self.list
    [
      "DMT",
      "LSD",
      "alcohol",
      "amphetamine",
      "marijuana",
      "opium",
      "psylocibin",
      "salvia"
    ]
  end
end

module ConsumptionMethodList
  def self.list
    [
      "smoked",
      "eaten",
      "crushed and snorted"
    ]
  end
end

module RepliesList
  def self.list
    [
      "The hunt is on. Search our website for savings on XX!",
      "Late winter is the time to really look at the bones of your garden & begin planning how to create or improve beds and borders.",
      "Late winter and early spring storms can be rough on XX. Gently remove the weight of heavy snow using a broom.",
      "There are 3 major nutrients XX require for good growth: nitrogen, phosphorus & potassium.",
      "Seed starting inside today for XX, YY, ZZ, AA, & BB!!",
      "Everyone at our seed exchanges gets a handy XX garden marker!",
      "XX splitting? Keep soil evenly moist but not wet; XX need 1-3 inches of water per week.",
      "Pick XX when the fruits are small, tender & the skin is shiny.  Production stops if fruits are left on the vine.",
      "XX is the most #interesting YY we have ever seen! It’s deliciously stunning.",
      "Container plants need frequent watering. You will know if enough water was given when it begins to seep out from the bottom.",
      "XX is bolt tolerant! This baby can withstand any harsh #weather conditions.",
      "XX produce flowers? Loosen soil under your plants to find a few to harvest.",
      "New XX are sweeter than mature XX.",
      "XX should be pruned to ground level after they have completed fruiting.",
      "Continue to deadhead XX to encourage continuous bloom.",
      "Harvesting XX—cut back whole stems to generate more flowers. Harvest is the morning when the flavor is at its peak.",
      "Make sure you eliminate all sources of stagnant water to help control mosquitoes.",
      "XX has proven many times to be a winner in flavor, productivity and wide adaptability.",
      "Cut flowers on a diagonal. It absorbs more water & prevents the base of the stem from resting on the bottom of the vase.",
      "XX need lots of watering & fertilizer. Fruits that aren't removed from the vine turn yellow & plants stop producing.",
      "There’s jealousy in the garden when XX blooms! It is strikingly beautiful.",
      "Thinning your plants is essential for healthy plant growth & development. Snip off the seedlings at their bases w/ scissors.",
      "To avoid damaging XX roots, the best time to position the cage in the garden is when you plant the seedlings.",
      "Walking through a wet garden or touching wet leaves spreads disease from one plant to another. Be careful when leaves are wet.",
      "In the mood for some XX Parm? XX is perfect for slicing, baking and roasting.",
      "Growing plants in containers? Remember to use containers w/ holes for drainage & use a good quality potting soil, not top soil.",
      "If nights are staying above 55 degrees, get your XX garden going.",
      "Spring has sprung! So direct sow XX, YY, ZZ, & AA.",
      "XX is the first ever YY with mild heat. You can bite into one like an apple and live to tell the tale!",
      "After the danger of frost has passed set out XX, YY, ZZ, and AA transplants. All are good border plants.",
      "What do you usually put in the ground first? Do you start off with spring XX or spring YY?",
      "Do you ever find these in your garden? In most places XX are one of the earliest signs that spring is on its way.",
      "XX seed sprouts don’t need soil or sunny windows. Rinse seeds every day & keep in a warm place. Ready for eating in 5-7 days.",
      "Early spring flowers means it’s time for XX bouquets.",
      "Cook’s love fresh herbs! ‘Culinary Classics Herb Plant Collection’ includes XX, YY, ZZ, & AA.",
      "Save space in a seed starting tray by placing 2 seeds in each cell. Cut off (not pull out) the weaker one. No more empty cells.",
      "Have some fun! Why not plant some flowers in your vegetable garden this spring?",
      "If your XX houseplants have brown tips there may not be enough humidity in your house. Place the pots on a tray of damp pebbles.",
      "What do you grow in your community garden?",
      "All-in-one 'XL Eco-Friendly Ultimate Growing System' seed-starting kit that has everything you need to grow, even the largest of seedlings.",
      "Zones 9 & 10 still have time to plant XX. Most stop producing once the temps remain above 85 degrees.",
      "Community gardens are popping up all over the Country. What do you like best about your community garden?",
      "February is National XX Month! Retweet if you love XXs!",
      "XX can need 10 weeks for spring planting.",
      "We’re over halfway through February! That means spring isn’t that far away. What are you looking forward to most this spring?",
      "Check your garden for any XX or YY that have heaved out. Gently press them back in the ground & mulch.",
      "This XX is pure “wow-factor.”",
      "Do you have a specific bouquet style? Take our poll!",
      "Get rid of any stored XX, YY & ZZ that are rotting or soft.",
      "Check XX & YY that have rotted or shriveled.",
      "Grow 24% more XX, 34% more YY & 47% more ZZ w/ ‘Sea Magic Organic Growth Activator.’ Feast on better tasting crops!",
      "XX is the new kid on the block. These darlings aren’t only gorgeous; they're loaded with big time #nutrition!",
      "Welcome to February! We are one month closer to spring, friends!",
      "What are you doing now to prep for your spring garden?",
      "Label your seeds with Popsicle sticks this winter…and then transfer them to the garden this spring! It’s a great way to keep track!",
      "Tell us what varieties you have got started inside (or outside if you’re in the South) this winter!",
      "Southern Zones 9-10 can sow XX, YY, ZZ, & AA outside now.",
      "Cooler zones can now start XX, YY, & ZZ indoors.",
      "It’s National XX Pie Day! Yum!",
      "Starting XX seeds indoors in Jan or Feb can help ensure blooms this summer.",
      "We have a seed-starting tip to start your week! Use clothespins to label your seeds so you know what’s what!",
      "I spend hours dreaming about what I want my garden to look like but minutes on labor. #TimetoChange",
      "Check with your local Park District to see if they will have a community garden program this spring. If not, encourage them to start one!",
      "Let’s fast forward to June! That’s when our XX begins to unleash fruit…Yum!",
      "Remove the clear plastic lid of your seed starting kit when 50% of seedlings have germinated to reduce risk of mold and mildew",
      "Bringing XX plants inside for winter can also bring unwanted pests.",
      "XX is a very hardy bulb. If it has begun to sprout, cover with 3-4 in. of mulch after the first few frosts to protect from hard freezes.",
      "New XX is our most colorful XX, ever.",
      "Crop rotation helps reduce soil disease. XX shouldn’t be planted in the same area year after year.",
      "To avoid white mold on top of soil with XX seedlings: Scrape off white crust & only water when soil no longer feels moist",
      "When thinning XX seedlings, it's best to cut the stem near the soil.",
      "Pulling XX seedlings can damage the roots of the plants you want to keep.",
      "You can leave your decorative winter planters out until the first signs of spring!",
      "Ever hear of aeroponics?",
      "XX at its finest! #gardening",
      "XX garland is so easy and fun to make. Put it on the tree, use it in a centerpiece or drape it across the mantel",
      "Today is National XX Day! Sharing starts…now!",
      "Offering up shimmery artisanal XX ornaments for the holidays",
      "Cats love nothing more than feasting on an abundance of XX.",
      "What’s your favorite animal in the garden?",
      "Some of the best furry friends in the garden are the ones that drop by unexpectedly — birds!",
      "Are you worried about potentially hazardous plants when your pets are in the garden?",
      "42 flowers you can eat? Who knew!",
      "Today is \"More XX, Less Salt\" Day! There's nothing better than fresh garden herbs in your favorite recipes!",
      "XX are a great cool-season flower.",
      "What are you planning to grow this fall?",
      "Prepare for cool-season gardening this year with cold frames!",
      "How do you like to eat your XX?",
      "What garden flowers do you use for home decorating or arrangements?",
      "What are you doing to fight drought and conserve water in your garden?",
      "How did you learn to garden?",
      "Did you try a new variety this year? Or did you stick with your favorites?",
      "What's your favorite way to entertain in the garden?",
      "Did you know that XX are technically a fruit and have been cultivated by humans for 6,000 years?",
      "Did you know that 93% of American gardening households grow XX?",
      "What is the last thing you plant in your garden?",
      "Do you think the XX is a fruit or vegetable? Either way they are still tasty!",
      "What is your favorite way to eat XX?",
      "XX is a breakthrough when it comes to taste, size, yield, and disease-resistance!",
      "There is no wrong choice when it comes to planting XX.",
      "Garden-fresh XX have a sweetness vastly superior to that of those bought in the store.",
      "Exclusive Offerings ~ Generational XX & Heirloom YY",
      "What do you think are the easiest flowers to grow?",
      "Sweet and delicious, XX are the perfect fruit to start growing in your garden!",
      "What flowers are starting to bloom in your garden now? Send us a picture!",
      "#Garden Tip: If the snow is gone now is the time to clean up the herb garden. Weed the whole garden...",
      "Combining the great taste of heirlooms with the sturdiness and resistance of hybrid roots, XX have it all",
      "Available in various sizes, shapes, tastes, and colors, XX are one of the easiest crops you can grow!",
      "Our widely adapted XX is easy to grow, rich in flavor and will keep up to 10 months after being harvested.",
      "#Garden Tip: As soon as the freeze is over, time to start in the vegetable garden.",
      "Come see XX this evening at the Flower Show!",
      "Perennials are plants that bloom year after year, providing beauty to the garden for seasons to come!",
      "XX are long-lived plants with a fresh fragrance that will flourish if planted in a well-drained, sunny spot.",
      "Birding and garden enthusiast spending a great amount of time enjoying nature",
      "You'll need stakes or cages to support XX plants to keep the fruit off the ground. Here are some support tips!",
      "Here are some quick tips to grow beautiful and delicious XX!",
      "Mix & Match 3 packs of your favorite XX, YY, and ZZ to create custom combinations!",
      "What is your favorite annual to start by seed?",
      "There are some lovely perennial XX that bloom early, even if there is still snow on the ground!",
      "I can't wait to get some XX!!",
      "We're here to help you grow the best & freshest XX in your own home. We have guides and tips!!",
      "Annuals add color to the garden all summer long and are easy to grow, giving your garden a new look!!",
      "#Garden Tip: If your XX little seedlings suddenly toppled over and died last year, try again!",
      "Would you rather have heavy rain for a week strait or a blizzard dropping 2 feet of snow all at once?",
      "#Gardening Tip: We often get asked: Why are my XX seedlings spindly? Light!",
      "#Garden Tip: XX are low care shrubs for the shade.",
      "Please share picture of your decorated XX.",
      "Question for today: What's in your garden — annuals, perennials, or a combination of both?",
      "Some of the newer XX varieties have bigger blooms & more flowers, but are less fragrant.",
      "All XX Plants— up to 35% off!",
      "Rooftop gardening is a growing idea. (pun intended)",
      "Have you done this before or are you trying it this year?",
      "Sort of takes the fun out of gardening... what do you think?",
      "I’m thinking of planting XX now for a spring bloom— what’s your favorite spring bulb?",
      "XX isn't popular for eating, but it has beautiful flowers and pods for fall wreaths.",
      "Cooking XX with great flavor & lots of nutrients is easy. And quick—just 5 minutes is all it takes.",
      "Good evening #gardenchat",
      "We see autumn as a new beginning for gardeners. Do you agree?",
      "XX stands up to cool temps. Plant now and harvest tender leaves in about 6 weeks.",
      "Think about some great edibles like XX or YY to add to existing pots for flair through fall.",
      "If you are expecting a frost tonight bring in or cover your tender XX.",
      "So, I think we all agree. Up is better. #gardenchat",
      "Homeland security makes you empty your water, but you can carry your XX on board lol",
      "XX is gardening for the future. Right on.",
      "Hi. There are so many great veggies and flowers that grow well verticle!",
      "Benefit of rain? Weeding will be really easy in the water softened earth. Weed away...",
      "Today celebrates several things. Among them — it is National XX Day.",
      "I've found XX germinate well with consistent moisture.",
      "XX can be planted now. Consider using them for ground cover around ornamental plants.",
      "Do you think of XX as a fall crop? They do well when you start them now.",
      "How would you complete this sentence: If I could only grow one thing in my garden, it would be_______.",
      "There's plenty of time to plant for fall harvest! You can put in XX, YY and even ZZ!!",
      "I find XX to be very rewarding crops! I'm trying fall XX this year.",
      "Making pickles is fun!",
      "You've watered your XX but they still look a droopy? It's the heat.",
      "If you're running a dehumidifier in your home, rather than flushing the water down the drain, use it to water your gardens.",
      "Is it ready to harvest? XX usually smell ripe.",
      "Is it ready to harvest? XX is ready when the husks are plump.",
      "Is it ready to harvest? XX should be cut while tightly formed.",
      "Is it ready to harvest? XX should be firm with shiny skin.",
      "Many of us lose steam for gardening when it gets this steamy outside! But our plants still need us. Baby them a bit.",
      "Everything does bloom! Even the most discreet XX puts out a tiny bloom in spring. #gardenchat",
      "Angry/sad, gardening=answer.",
      "Teach your children to enjoy XX fresh off the vine.",
      "Look for XX and give it plenty of room to romp!",
      "Did you know July is National XX month? A truly reward plant to grow. Beautiful and productive.",
      "Don't fertilize plants stressed by drought, heat or pests. Promoting new growth will stress plant further.",
      "XX can be harvested at several stages.",
      "RAIN, RAIN GO AWAY!",
      "Can your phone help you garden?",
      "Do you have uninvited guests visiting your garden? Plants with prickly leaves or thorns are great barrier plants...",
      "Stolen XX? What's the world coming to...",
      "Gardeners are happier and healthier.",
      "What is the bright round thing in the sky? Oh it's the sun- finally! Do you see it too?",
      "If you're looking for a fresh flower that will tolerate a little shade and add life to containers, XX is super cute...",
      "Our customer service and order lines are open today!",
      "Did you know you can protect your XX plants from cutworms by simply wrapping the stem with cardboard?",
      "Have you checked out the moon tonight? It's Bright and Beautiful!",
      "Anxious to get out and garden but not sure where to start? XX!",
      "This is a good time to cut down XX...",
      "Snow is the best thing that could happen to the garden.",
      "I see that something has found a home in my garden. I have a vole.",
      "Can you name this XX variety?",
      "Good news to those who love XX! We were able to get a small supply of seeds for this year.",
      "Start Seeds indoors or buy plants? What do you do for your garden and why?",
      "House plants are beneficial in many ways. They clean the air!",
      "Did anyone else read about the XX? It is now the world's hottest!",
      "The Best XX To Grow Indoors This Winter",
      "Brighten the holidays for your gardening friends by including packets of seeds!",
      "Although popular, braiding XX to hang in the kitchen is not the best way to preserve them.",
    ]
  end
end
